export const ItemsPackage = [
  {
    id: 1,
    title: "Blog Site",
    images: [
      {
        original: "./blog ss1.png",
        thumbnail: "./blog ss1.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss2.png",
        thumbnail: "./blog ss2.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss3.png",
        thumbnail: "./blog ss3.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss4.png",
        thumbnail: "./blog ss4.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss5.png",
        thumbnail: "./blog ss5.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss6.png",
        thumbnail: "./blog ss6.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss7.png",
        thumbnail: "./blog ss7.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss8.png",
        thumbnail: "./blog ss8.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss9.png",
        thumbnail: "./blog ss9.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
    ],
    desc: "A blog site built in React, SCSS, MySQL and Express, used JSONWebToken for authorizing users, ReactQuill to let the user use bold, italic, bullets etc",
    ghlink: "https://github.com/Ahmad-Shawish/blog",
    tunnel: "https://sqb9npfb-3000.euw.devtunnels.ms/",
  },
  {
    id: 2,
    title: "Movie Search",
    images: [
      {
        original: "./movie ss1.png",
        thumbnail: "./movie ss1.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie full popular.png",
        thumbnail: "./movie full popular.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie ss3.png",
        thumbnail: "./movie ss3.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie ss4.png",
        thumbnail: "./movie ss4.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie ss5.png",
        thumbnail: "./movie ss5.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie ss6.png",
        thumbnail: "./movie ss6.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie ss7.png",
        thumbnail: "./movie ss7.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie ss8.png",
        thumbnail: "./movie ss8.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
    ],
    desc: "A movie searching site built in React, SCSS, and utilized The Movie Database (TMDB) API",
    ghlink: "https://github.com/Ahmad-Shawish/moviezSearch",
    tunnel: "https://sqb9npfb-5173.euw.devtunnels.ms/",
  },
  {
    id: 3,
    title: "MapPing App",
    images: [
      {
        original: "./map ss1.png",
        thumbnail: "./map ss1.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./map ss2.png",
        thumbnail: "./map ss2.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./map ss3.png",
        thumbnail: "./map ss3.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./map ss4.png",
        thumbnail: "./map ss4.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
    ],
    desc: "A site to add pings on the map to tell about visited places and countries with ratings, built with React, CSS, MongoDB, Express, and the map provided by MapBox",
    ghlink: "https://github.com/Ahmad-Shawish/mapPin",
    tunnel: "https://sqb9npfb-3001.euw.devtunnels.ms/",
  },
  {
    id: 4,
    title: "Car Renting",
    images: [
      {
        original: "./carrent ss1.jpeg",
        thumbnail: "./carrent ss1.jpeg",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./carrent ss2.jpeg",
        thumbnail: "./carrent ss2.jpeg",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./carrent ss3.jpeg",
        thumbnail: "./carrent ss3.jpeg",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./carrent ss4.jpeg",
        thumbnail: "./carrent ss4.jpeg",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./carrent ss5.png",
        thumbnail: "./carrent ss5.png",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./carrent ss6.png",
        thumbnail: "./carrent ss6.png",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./carrent ss7 (2).png",
        thumbnail: "./carrent ss7 (2).png",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
    ],
    desc: "Frontend design only from Figma, built with React and SCSS",
    ghlink: "https://github.com/Ahmad-Shawish/carRent-FEdesignFigma",
    tunnel: "https://sqb9npfb-5174.euw.devtunnels.ms/",
    flink:
      "https://www.figma.com/community/file/1138316365849534403/car-rent-website-design-pickolab-studio",
  },
  {
    id: 5,
    title: "(React Native) Social App",
    images: [
      {
        original: "./rn-social ss1.png",
        thumbnail: "./rn-social ss1.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss2.png",
        thumbnail: "./rn-social ss2.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss3.png",
        thumbnail: "./rn-social ss3.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss4.png",
        thumbnail: "./rn-social ss4.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss5.png",
        thumbnail: "./rn-social ss5.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss6.png",
        thumbnail: "./rn-social ss6.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss7.png",
        thumbnail: "./rn-social ss7.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss8.png",
        thumbnail: "./rn-social ss8.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss9.png",
        thumbnail: "./rn-social ss9.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
    ],
    desc: "This is a simple front end React Native project to get started and familiarize myself with it, the design is basic and straight forward with plans to continue on it and add the backend. Made with Expo, Expo Router and NativeWind(Tailwind for React Native)",
    ghlink: "https://github.com/Ahmad-Shawish/RN-Social",
  },
];

export const ItemsVanila = [
  {
    id: 1,
    title: "Blog Site",
    images: {
      img1: "./blog ss1.png",
      img2: "./blog ss2.png",
      img3: "./blog ss3.png",
      img4: "./blog ss4.png",
      img5: "./blog ss5.png",
      img6: "./blog ss6.png",
      img7: "./blog ss7.png",
      img8: "./blog ss8.png",
      img9: "./blog ss9.png",
    },
    desc: "A blog site built in React, SCSS, MySQL and Express, used JSONWebToken for authorizing users, ReactQuill to let the user use bold, italic, bullets etc",
    ghlink: "https://github.com/Ahmad-Shawish/blog",
    tunnel: "https://sqb9npfb-3000.euw.devtunnels.ms/",
  },
  {
    id: 2,
    title: "Movie Search",
    images: {
      img1: "./movie ss1.png",
      img2: "./movie full popular.png",
      img3: "./movie ss3.png",
      img4: "./movie ss4.png",
      img5: "./movie ss5.png",
      img6: "./movie ss6.png",
      img7: "./movie ss7.png",
      img8: "./movie ss8.png",
    },
    desc: "A movie searching site built in React, SCSS, and utilized The Movie Database (TMDB) API",
    ghlink: "https://github.com/Ahmad-Shawish/moviezSearch",
    tunnel: "https://sqb9npfb-5173.euw.devtunnels.ms/",
  },
  {
    id: 3,
    title: "MapPing App",
    images: {
      img1: "./map ss1.png",
      img2: "./map ss2.png",
      img3: "./map ss3.png",
      img4: "./map ss4.png",
    },
    desc: "A site to add pings on the map to tell about visited places and countries with ratings, built with React, CSS, MongoDB, Express, and the map provided by MapBox",
    ghlink: "https://github.com/Ahmad-Shawish/mapPin",
    tunnel: "https://sqb9npfb-3001.euw.devtunnels.ms/",
  },
  {
    id: 4,
    title: "Car Renting",
    images: {
      img1: "./carrent ss1.jpeg",
      img2: "./carrent ss2.jpeg",
      img3: "./carrent ss3.jpeg",
      img4: "./carrent ss4.jpeg",
      img5: "./carrent ss5.png",
      img6: "./carrent ss6.png",
      img7: "./carrent ss7 (2).png",
    },
    desc: "Frontend design only from Figma, built with React and SCSS",
    ghlink: "https://github.com/Ahmad-Shawish/carRent-FEdesignFigma",
    tunnel: "https://sqb9npfb-5174.euw.devtunnels.ms/",
    flink:
      "https://www.figma.com/community/file/1138316365849534403/car-rent-website-design-pickolab-studio",
  },
  {
    id: 5,
    title: "(React Native) Social App",
    images: {
      img1: "./rn-social ss1.png",
      img2: "./rn-social ss2.png",
      img3: "./rn-social ss3.png",
      img4: "./rn-social ss4.png",
      img5: "./rn-social ss5.png",
      img6: "./rn-social ss6.png",
      img7: "./rn-social ss7.png",
      img8: "./rn-social ss8.png",
      img9: "./rn-social ss9.png",
    },
    desc: "This is a simple front end React Native project to get started and familiarize myself with it, the design is basic and straight forward with plans to continue on it and add the backend. Made with Expo, Expo Router and NativeWind(Tailwind for React Native)",
    ghlink: "https://github.com/Ahmad-Shawish/RN-Social",
  },
];

export const newItems = [
  {
    id: 1,
    title: "Ecommerce Shop",
    images: [
      {
        original: "./shop ss1.png",
        thumbnail: "./shop ss1.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./shop ss2.png",
        thumbnail: "./shop ss2.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./shop ss3.png",
        thumbnail: "./shop ss3.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./shop ss4.png",
        thumbnail: "./shop ss4.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./shop ss5.png",
        thumbnail: "./shop ss5.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./shop ss6.png",
        thumbnail: "./shop ss6.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./shop ss7.png",
        thumbnail: "./shop ss7.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./shop ss8.png",
        thumbnail: "./shop ss8.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./shop ss9.png",
        thumbnail: "./shop ss9.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./shop ss10.png",
        thumbnail: "./shop ss10.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./shop ss11.png",
        thumbnail: "./shop ss11.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./shop ss12.png",
        thumbnail: "./shop ss12.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
    ],
    desc: "An ecommerce furniture shop site built with Nextjs, TailwindCSS and Strapi CMS, and used Redux for global state managment",
    ghlink: "https://github.com/Ahmad-Shawish/Furniro-nextjs-strapi",
    tunnel: "https://sqb9npfb-3002.euw.devtunnels.ms/",
  },
  {
    id: 2,
    title: "Blog Site",
    images: [
      {
        original: "./blog ss1.png",
        thumbnail: "./blog ss1.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss2.png",
        thumbnail: "./blog ss2.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss3.png",
        thumbnail: "./blog ss3.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss4.png",
        thumbnail: "./blog ss4.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss5.png",
        thumbnail: "./blog ss5.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss6.png",
        thumbnail: "./blog ss6.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss7.png",
        thumbnail: "./blog ss7.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss8.png",
        thumbnail: "./blog ss8.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./blog ss9.png",
        thumbnail: "./blog ss9.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
    ],
    desc: "A blog site built in React, SCSS, MySQL and Express, used JSONWebToken for authorizing users, ReactQuill to let the user use bold, italic, bullets etc",
    ghlink: "https://github.com/Ahmad-Shawish/blog",
    tunnel: "https://sqb9npfb-3000.euw.devtunnels.ms/",
  },
  {
    id: 3,
    title: "Gym Landing Page",
    images: [
      {
        original: "./gym ss1.png",
        thumbnail: "./gym ss1.png",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./gym ss2.png",
        thumbnail: "./gym ss2.png",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./gym ss3.png",
        thumbnail: "./gym ss3.png",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./gym ss4.png",
        thumbnail: "./gym ss4.png",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./gym ss5.png",
        thumbnail: "./gym ss5.png",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./gym ss6 new.png",
        thumbnail: "./gym ss6 new.png",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./gym ss7.png",
        thumbnail: "./gym ss7.png",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./gym ss8.png",
        thumbnail: "./gym ss8.png",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./gym ss9.png",
        thumbnail: "./gym ss9.png",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
    ],
    desc: "Frontend design of a gym landing page from Figma, built with React and SCSS",
    ghlink: "https://github.com/Ahmad-Shawish/Gym-LandingPage",
    tunnel: "https://sqb9npfb-5174.euw.devtunnels.ms/",
    // flink:
    //   "https://www.figma.com/community/file/1138316365849534403/car-rent-website-design-pickolab-studio",
  },
  {
    id: 4,
    title: "Movie Search",
    images: [
      {
        original: "./movie ss1.png",
        thumbnail: "./movie ss1.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie full popular.png",
        thumbnail: "./movie full popular.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie ss3.png",
        thumbnail: "./movie ss3.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie ss4.png",
        thumbnail: "./movie ss4.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie ss5.png",
        thumbnail: "./movie ss5.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie ss6.png",
        thumbnail: "./movie ss6.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie ss7.png",
        thumbnail: "./movie ss7.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./movie ss8.png",
        thumbnail: "./movie ss8.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
    ],
    desc: "A movie searching site built in React, SCSS, and utilized The Movie Database (TMDB) API",
    ghlink: "https://github.com/Ahmad-Shawish/moviezSearch",
    tunnel: "https://sqb9npfb-5173.euw.devtunnels.ms/",
  },
  {
    id: 5,
    title: "MapPing App",
    images: [
      {
        original: "./map ss1.png",
        thumbnail: "./map ss1.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./map ss2.png",
        thumbnail: "./map ss2.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./map ss3.png",
        thumbnail: "./map ss3.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
      {
        original: "./map ss4.png",
        thumbnail: "./map ss4.png",
        thumbnailWidth: "100px",
        thumbnailHeight: "60px",
        originalHeight: "450px",
        loading: "lazy",
      },
    ],
    desc: "A site to add pings on the map to tell about visited places and countries with ratings, built with React, CSS, MongoDB, Express, and the map provided by MapBox",
    ghlink: "https://github.com/Ahmad-Shawish/mapPin",
    tunnel: "https://sqb9npfb-3001.euw.devtunnels.ms/",
  },
  {
    id: 6,
    title: "(React Native) Social App",
    images: [
      {
        original: "./rn-social ss1.png",
        thumbnail: "./rn-social ss1.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss2.png",
        thumbnail: "./rn-social ss2.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss3.png",
        thumbnail: "./rn-social ss3.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss4.png",
        thumbnail: "./rn-social ss4.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss5.png",
        thumbnail: "./rn-social ss5.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss6.png",
        thumbnail: "./rn-social ss6.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss7.png",
        thumbnail: "./rn-social ss7.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss8.png",
        thumbnail: "./rn-social ss8.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
      {
        original: "./rn-social ss9.png",
        thumbnail: "./rn-social ss9.png",
        thumbnailHeight: "60px",
        originalHeight: "500px",
        loading: "lazy",
      },
    ],
    desc: "This is a simple front end React Native project to get started and familiarize myself with it, the design is basic and straight forward with plans to continue on it and add the backend. Made with Expo, Expo Router and NativeWind(Tailwind for React Native)",
    ghlink: "https://github.com/Ahmad-Shawish/RN-Social",
  },
];

export const newItemsVanila = [
  {
    id: 1,
    title: "Ecommerce Shop",
    images: {
      img1: "./shop ss1.png",
      img2: "./shop ss2.png",
      img3: "./shop ss3.png",
      img4: "./shop ss4.png",
      img5: "./shop ss5.png",
      img6: "./shop ss6.png",
      img7: "./shop ss7.png",
      img8: "./shop ss8.png",
      img9: "./shop ss9.png",
      img10: "./shop ss10.png",
      img11: "./shop ss11.png",
      img12: "./shop ss12.png",
    },
    desc: "An ecommerce furniture shop site built with Nextjs, TailwindCSS and Strapi CMS, and used Redux for global state managment",
    ghlink: "https://github.com/Ahmad-Shawish/Furniro-nextjs-strapi",
    tunnel: "https://sqb9npfb-3002.euw.devtunnels.ms/",
  },
  {
    id: 2,
    title: "Blog Site",
    images: {
      img1: "./blog ss1.png",
      img2: "./blog ss2.png",
      img3: "./blog ss3.png",
      img4: "./blog ss4.png",
      img5: "./blog ss5.png",
      img6: "./blog ss6.png",
      img7: "./blog ss7.png",
      img8: "./blog ss8.png",
      img9: "./blog ss9.png",
    },
    desc: "A blog site built in React, SCSS, MySQL and Express, used JSONWebToken for authorizing users, ReactQuill to let the user use bold, italic, bullets etc",
    ghlink: "https://github.com/Ahmad-Shawish/blog",
    tunnel: "https://sqb9npfb-3000.euw.devtunnels.ms/",
  },
  {
    id: 3,
    title: "Gym Landing Page",
    images: {
      img1: "./gym ss1.png",
      img2: "./gym ss2.png",
      img3: "./gym ss3.png",
      img4: "./gym ss4.png",
      img5: "./gym ss5.png",
      img6: "./gym ss6 new.png",
      img7: "./gym ss7.png",
      img8: "./gym ss8.png",
      img9: "./gym ss9.png",
    },
    desc: "Frontend design of a gym landing page from Figma, built with React and SCSS",
    ghlink: "https://github.com/Ahmad-Shawish/Gym-LandingPage",
    tunnel: "https://sqb9npfb-5174.euw.devtunnels.ms/",
    // flink:
    //   "https://www.figma.com/community/file/1138316365849534403/car-rent-website-design-pickolab-studio",
  },
  {
    id: 4,
    title: "Movie Search",
    images: {
      img1: "./movie ss1.png",
      img2: "./movie full popular.png",
      img3: "./movie ss3.png",
      img4: "./movie ss4.png",
      img5: "./movie ss5.png",
      img6: "./movie ss6.png",
      img7: "./movie ss7.png",
      img8: "./movie ss8.png",
    },
    desc: "A movie searching site built in React, SCSS, and utilized The Movie Database (TMDB) API",
    ghlink: "https://github.com/Ahmad-Shawish/moviezSearch",
    tunnel: "https://sqb9npfb-5173.euw.devtunnels.ms/",
  },
  {
    id: 5,
    title: "MapPing App",
    images: {
      img1: "./map ss1.png",
      img2: "./map ss2.png",
      img3: "./map ss3.png",
      img4: "./map ss4.png",
    },
    desc: "A site to add pings on the map to tell about visited places and countries with ratings, built with React, CSS, MongoDB, Express, and the map provided by MapBox",
    ghlink: "https://github.com/Ahmad-Shawish/mapPin",
    tunnel: "https://sqb9npfb-3001.euw.devtunnels.ms/",
  },
  {
    id: 6,
    title: "(React Native) Social App",
    images: {
      img1: "./rn-social ss1.png",
      img2: "./rn-social ss2.png",
      img3: "./rn-social ss3.png",
      img4: "./rn-social ss4.png",
      img5: "./rn-social ss5.png",
      img6: "./rn-social ss6.png",
      img7: "./rn-social ss7.png",
      img8: "./rn-social ss8.png",
      img9: "./rn-social ss9.png",
    },
    desc: "This is a simple front end React Native project to get started and familiarize myself with it, the design is basic and straight forward with plans to continue on it and add the backend. Made with Expo, Expo Router and NativeWind(Tailwind for React Native)",
    ghlink: "https://github.com/Ahmad-Shawish/RN-Social",
  },
];
